server:
  port: 9191
  
spring:
   application:
      name: API-GATWAY
   cloud:
      gatway:
        routes:
          - id: USER-SERVICE
            url: lb://USER-SERVICE 
            predicates:
              - Path=/users/**
            filters:
              - name: CircuitBreaker
                args:
                  name: USER-SERVICE
                  fallbackuri: forward:/userServicefallback
          - id: DEPARTMENT-SERVICE
            url: lb://DEPARTMENT-SERVICE 
            predicates:
              - Path=/departments/**
            filters:
              - name: CircuitBreaker
                args:
                  name: DEPARTMENT-SERVICE
                  fallbackuri: forward:/departmentServicefallback
                  
hystrix:
  command:
     fallbackmd:
        execution:
           isolation:
             thread:
               timeoutInMilliseconds: 4000
               
management:
   endpoints:
      web:
         explosure:
           include: hystrix.stream
           
      
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://localhot:8761/eureka/
instance:
    hostname: localhost